version: '3.8'

services:
  lightning-webapp:
    build: .
    container_name: singapore-lightning-detection
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=lightning-detection"
      - "description=Singapore Lightning Detection Web Application"

# Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: lightning-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lightning-webapp
    restart: unless-stopped
    profiles:
      - "production"

networks:
  default:
    name: lightning-detection-network